---

- hosts: 10.7.2.13
  gather_facts: false
  tasks:
  
     - name:
       ios_l2_interface:
         name: interface GigabitEthernet3/2
         mode: access
         access_vlan: 2


   # - name: Ensure GigabitEthernet0/5 is configured for access vlan 20
   #   ios_config:
   #     lines:
   #      - switchport access vlan 2
   #      - no negotiation auto
   #      - spanning-tree portfast edge
   #      - spanning-tree bpduguard enable
   #     parents: interface GigabitEthernet3/2
   #     match: exact
   #     replace: block
   #   register: interface
   #
   # - debug:
   #     msg: "{{ interface }}"
