---

# use the following command line ansible-playbook playbook_qa.yml --extra-vars "@roles/qa_slot_vlans/files/qa_slot_large2_series5.yml"

- hosts: qa_5ks
  gather_facts: false
  connection: local
  roles:
    - roles/qa_slot_vlans
