---

- name: Nexus 5k - Create VLANs in VLAN database
  nxos_config:
    lines:
     - name {{ name + '-' + item.vlanid}}
    parents: vlan {{ item.vlanid }}
  loop: "{{ vlans }}"

- name: Nexus 5k - Add vlan to trunk Port-Channel 1
  nxos_config:
    lines:
     - switchport trunk allowed vlan add {{ item.vlanid }}
    parents: interface port-channel1
  loop: "{{ vlans }}"

- name: Nexus 5k - Add vlan to trunk Port-Channel 2
  nxos_config:
    lines:
      - switchport trunk allowed vlan add {{ item.vlanid }}
    parents: interface port-channel2
  loop: "{{ vlans }}"
