---

 - name: find all logging hosts and register to variable
   ios_command:
    commands: show run | in logging_host
   register: loggingHostOutput

 # - name: display loggingHost
 #   debug:
 #     msg: "{{ loggingHost }}"

 - name: Parse the "show run | in logging_host" for only the IP address
   set_fact:
     loggingHostIPs: "{{ loggingHostOutput.stdout[0] | parse_cli('./roles/switch_base_config/files/loggingHostIP.yml')}}"

 # - name: display loggingHostIPs keys
 #   debug:
 #     msg: "{{ loggingHostIPs.hosts.keys() }}"

 - name: Remove logging to hosts that are not in use (if they exist)
   ios_config:
     lines: no logging host {{ item }}
   when: "logging_host not in item "
   with_items: "{{ loggingHostIPs.hosts.keys() }}"


 - name: add logging to hosts
   ios_logging:
       dest: host
       name: "{{ logging_host }}"
       state: present
