---

 # - name: Configure slot vlan on QA Nexus 5000
 #   hosts: qa_5ks
 #   gather_facts: false
 #   connection: network_cli
 #   tasks:
 #
 #   vars:
 #     LGPROP2:
 #      - { vlan_id: '761', vlan_name: 'LGPROP2-761' }
 #      - { vlan_id: '762', vlan_name: 'LGPROP2-762' }
 #      - { vlan_id: '763', vlan_name: 'LGPROP2-761' }
 #      - { vlan_id: '765', vlan_name: 'LGPROP2-762' }
 #      - { vlan_id: '3907', vlan_name: 'LGPROP2-3907' }
 #
 #
 #      - name: Configure Vlan
 #        nxos_config:
 #          lines:
 #            - name {{ item.vlan_name }}
 #          parents: vlan {{ item.vlan_id}}
 #        loop: "{{ LGPROP2 }}"
 #
 #      - name: Add vlan to trunk Port-Channel 1
 #        nxos_config:
 #          lines:
 #            - switchport trunk allowed vlan add {{ item.vlan_id }}
 #          parents: interface port-channel1
 #        loop: "{{ LGPROP2 }}"
 #
 #      - name: Add vlan to trunk Port-Channel 2
 #        nxos_config:
 #          lines:
 #            - switchport trunk allowed vlan add {{ item.vlan_id }}
 #          parents: interface port-channel2
 #        loop: "{{ LGPROP2 }}"

 - name: Configure slot vlan on UCS
   hosts: jayr_qa_ucs
   gather_facts: false
   connection: local
   vars_files:
    - qa_slot_large2.yml

   tasks:




    - name: Configure VLAN
      ucs_vlans:
       hostname: 192.168.128.132
       username: ucspe
       password: ucspe
       name: "{{ slot_property_name + '-' + item.vlanid }}"
       id: '{{ item.vlanid }}'
      loop: "{{ vlans }}"
